theme: jekyll-theme-minimal
title: 'Motivation for compile time if in C++'
description: 'Motivation for compile time if (if constexpr) in C++'
author: 'Gaurav Sehgal'
twitter:
    username: gaurav__sehgal
